### ISSUE TITLE
cbv 사용

### ISSUE THREAD

**Issue by calvin** [spellcheck-ko/galkwi#6]
중복된 view 코드가 많은 것 같은데 function views보다 [class-based views](https://docs.djangoproject.com/en/1.10/topics/class-based-views/)를 사용하는 것이 어떨까 싶습니다.

괜찮다면 CBV 코드를 PR 하겠습니다.

**Comment by changwoo** [comment]
네네 좋지요.

**Comment by calvin** [comment]
#8 WIP PR을 열었습니다.

**Comment by changwoo** [comment]
감사합니다. 머지되었습니다!

**Comment by changwoo** [comment]
/entry/ 에서 검색 기능이 동작하지 않네요. EntryIndexView

**Comment by changwoo** [comment]
/search/add에서 "저장하고 새 제안 추가"로 추가하는 경우 예외 발생합니다. 

```
Internal Server Error: /suggestion/add/
Traceback (most recent call last):
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 1050, in render
    return render_value_in_context(output, context)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/template/base.py", line 1028, in render_value_in_context
    value = force_text(value)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/utils/html.py", line 391, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/forms/forms.py", line 123, in __str__
    return self.as_table()
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/forms/forms.py", line 271, in as_table
    errors_on_separate_row=False)
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/forms/forms.py", line 188, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/forms/forms.py", line 297, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
  File "/home/cwryu/hacks/spell/galkwi/venv/lib/python3.5/site-packages/django/forms/forms.py", line 160, in errors
    if self._errors is None:
AttributeError: 'SuggestionEditForm' object has no attribute '_errors'
[18/Feb/2017 19:06:31] "POST /suggestion/add/ HTTP/1.1" 500 173693
```

**Comment by changwoo** [comment]
이 문제는 제가 수정한 부분과 연결되어 있네요. 수정 완료. b0cb8d8c2bb35c0fdd476fb54a5842d253922378

**Comment by changwoo** [comment]
@calvin EntryIndexView에서 검색하고 한 페이지가 넘어갈 때 다음/이전 링크에 파라미터로 page만 들어가네요.

예: https://galkwi.pyok.org/entry/?word=클

**Comment by changwoo** [comment]
머지되었습니다. 감사합니다.
